version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: querystringify
    versions:
    - 2.2.0
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: yargs-parser
    versions:
    - 10.1.0
  - dependency-name: mem
    versions:
    - 4.3.0
  - dependency-name: braces
    versions:
    - 2.3.2
  - dependency-name: clean-css
    versions:
    - 4.2.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: react-dom
    versions:
    - 16.2.1
  - dependency-name: webpack-dev-server
    versions:
    - 3.2.1
  - dependency-name: url-parse
    versions:
    - 1.4.7
  - dependency-name: sshpk
    versions:
    - 1.16.1
  - dependency-name: eslint-config-airbnb
    versions:
    - 17.1.0
  - dependency-name: extend
    versions:
    - 3.0.2
  - dependency-name: deep-extend
    versions:
    - 0.6.0
